# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 20:33
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notes',
            managers=[
                ('notesMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
